---
- name: Fedora Configuration Script
  hosts: localhost
  become: true

  tasks:
  - name: "Include vars files"
    include_vars:
      dir: '../vars'
        
  - name: "Install core packages"
    include: install_core_packages.yml

  - name: "Install gnome extensions"
    include: install_gnome_extensions.yml

    # Waiting on Ansible 2.4 to go GA
    #  - name: "Configure gnome"
    #include: configure_gnome.yml

...
