---
- name: Fedora Configuration Script
  hosts: localhost

  tasks:
  - name: "Include vars files"
    include_vars:
      dir: '../vars'
        
  - name: "Install core packages"
    include: install_core_packages.yml
...
